# Generated by Django 4.1.7 on 2023-03-25 12:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("short_description", models.CharField(max_length=200)),
                ("content", models.TextField(blank=True)),
                ("date", models.DateField(default=django.utils.timezone.now)),
                ("author", models.CharField(max_length=200)),
                ("post_image", models.ImageField(blank=True, upload_to="photos/%Y/%m")),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="MyBlog.category",
                    ),
                ),
            ],
        ),
    ]
